name: CI-CD-to-EKS

on:
  workflow_dispatch:
     
env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: boardgame
jobs:
  build-test-deploy:
    name: build & test
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
  
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
    
      - name: build with Maven
        run: mvn package
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::506334646887:role/github-role
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, Tag, and Push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
      - name: Install Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        
      - name: Install aws-iam-authenticator
        run: |
          curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.27.10/2024-03-18/bin/linux/amd64/aws-iam-authenticator
          chmod +x ./aws-iam-authenticator
          sudo mv aws-iam-authenticator /usr/local/bin/
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name gowrinath --region ${{ env.AWS_REGION }}
    
        
         








        


