name: Deploy Java APP new

on:
  push:
    branches: [main]
  
jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Install Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distrbution: 'temurin'
    - name: Build jar file
      run: mvn clean install 
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build and push Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
       docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
       docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
       docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
       
      
  

